### ISSUE TITLE
TO TEST on some dataset 

### ISSUE THREAD

**Issue by aimaaonline** [MahmoudWahdan/Siamese-Sentence-Similarity#2]
kindly help me to test ur trained model on some data set.please mention the steps

**Comment by MahmoudWahdan** [comment]
All details mentioned in README.md under "Testing the model with SICK-like data" section

python test.py --model=/path/to/model/model.h5 --word2vec=/path/to/word2vec/GoogleNews-vectors-negative300.bin --data=/path/to/sick/SICK.txt  --save=/path/to/save/location/test.csv
